### ISSUE TITLE
Where is models?

### ISSUE THREAD

**Issue by ruze00** [pat749/Stock-market-prediction-app#2]
I cannot find the models which are being imported from in `train_models.py`:

```
from models.linear_regression import LinearRegression
from models.svr import SupportVectorRegression
from models.linear_index_regression import LinearIndexRegression
from models.svr_index_regression import SupportVectorIndexRegression
from models.dnn_regression import DenseNeuralNetwork
```

Is this a missing file, module or external module?

**Comment by pat749** [comment]
it's an external module.

**Comment by ruze00** [comment]
I'm sorry, which one is that?

For example, this one: 

```from models.linear_regression import LinearRegression```

is not found.  Trying to use explicit import from either:

`sklearn.linear_model` or
`statistics`

Neither of these modules seem to provide the valid import.  `DenseNeuralNetwork` is not found at all.

Environment: clean venv from `requirements.txt`.

**Comment by pat749** [comment]
OK SOME FILE HAVE NOT BEEN IMPORTED TILL NOW AND CURRENTLY I AM EXPANDING IT SO I HAVE NOT UPLOADED WHOLE FILE BUT FOR REFERENCES I WILL SEND YOU DENSE NEURAL NETWORK IF YOU WANT TO SEE IT ON YOUR PERSONAL EMAIL.
